eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost


server:
  port: 100
spring:
  application:
    name: player-service
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  cloud:
    kubernetes:
      enabled: false


dekorate:
  docker:
    image: fbiankevin/